### ISSUE TITLE
Add cagov color scheme

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Services/California-State-Web-Template#225]
Add new cagov color scheme and make it default
Here is Design System cagov the color samples: 
https://designsystem.webstandards.ca.gov/style/design/#color

![Screen Shot 2022-03-25 at 9 57 12 AM](https://user-images.githubusercontent.com/31669748/160166673-26acd7ea-6bf1-403c-ab5b-de1937cbfa71.png)

**Comment by kkoryaka** [comment]
@Courtney-Chittock  I have added side navigation to the color scheme pages and added swatches to the color scheme landing page. So, it should be easy for user to go between them. 
![Screen Shot 2022-05-05 at 5 18 02 PM](https://user-images.githubusercontent.com/31669748/167047193-821a4f9f-a718-4f1b-a777-53505b1e025a.png)

Here is beta staging link for your review, I still need to add CA,gov color scheme in there.
https://as-cdt-pub-migr-betaws-ww-p-001-stage.azurewebsites.net/sample/color-schemes.html

**Comment by sharon-rabang** [comment]
[#280 Create new Visual Design landing page](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/280): This issue is related to the new Colors page. Will document the Colors' work in progress in #280, too.

**Comment by sharon-rabang** [comment]
Notes from related issue #280:
Had meeting to discuss how we can simplify the Color pages and avoid duplicating content.
- Walked through explorations for feedback.
- Learned the Color Theme pages are actually a single page with code that changes the example colors when selected in the local side navigation. Will keep this approach and do usability testing to find out if seeing examples in different colors is useful.
- Will update the prototypes in Figma for consistent design elements between the Color page and the Color Theme page.
- Will let Greg know when these pages are ready for dev.

**Comment by yesenia-gtz** [comment]
Moving to current sprint

**Comment by sharon-rabang** [comment]
Moving this issue to 'Ready for dev' since it's related to [#280](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/280) and [#512](https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/512).

Notes from 10.12.22: Visual design: [Website Template Color Palette](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=72%3A9374) colors have been applied to all prototype pages in Figma.

Same comments from https://github.com/Office-of-Digital-Services/California-State-Web-Template/issues/512:
@Greg-Watanabe These prototype pages are ready for dev in Figma:

[Colors](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4466)
[Color themes - Delta](https://www.figma.com/file/nVVip6nhCxHQnzPUnVf1bb/V6--State-Web-Template-official?node-id=2%3A4250)
Please update the the theme page's header and footer colors to match the website's colors (example: Statewide header = Primary color, Search bar = Gray 600, etc.).

Please let us know if we can help with any questions. Thanks!

**Comment by kkoryaka** [comment]
@sharon-rabang i am closing this one. there will be a new issue for header colors update

**Comment by yesenia-gtz** [comment]
@kkoryaka can you please link the new issue you mentioned would be opened above here?
